### ISSUE TITLE
SwiftMailer 6 support.

### ISSUE THREAD

**Issue by NikoGrano** [thecodingmachine/swift-twig-mail-template#10]
Cannot be installed with composer when using swiftmailer 6. Can this be issue?

**Comment by NikoGrano** [comment]
Unmaintained... pfff

**Comment by moufmouf** [comment]
Hey @Niko9911,

Sorry. Indeed, we are not using this library internally on our projects anymore, so it is unlikely we are going to invest time to move to SwiftMailer 6 (furthermore, Symfony and it's new mailer component makes the need for this library moot). Nevertheless, if you want to provide a PR, I'll hapilly merge it.
